In [2]:
import pandas as pd
from scipy.stats import chi2_contingency
#excel_file_path = 'thinkaloud_action_level_data.csv'
df  = pd.read_csv("thinkaloud_action_level_data.csv")
#print(df.columns)
#correctness_false_df = df[df['Correctness'] == "FALSE"]
df.head()

,Problem.ID,ProblemStep,User.ID,Problem.Sub.Part.ID,Order,Action.Type,Timestamp,Answer.Text,Correctness,Problem.Log.ID,Condition,Participant_ID,Problem,CorrectAnswer
0,"""PRABMQV2""",0,617499,1751056,2,"""answer""","""01/16/2020 16:42:58.145""","""2""",True,218467966,Proactive,thinkaloudp0216,4,NaN
1,"""PRABMQV2""",0,618040,1751056,1,"""start""","""01/24/2020 14:26:54.267""","""""",NaN,218676720,Proactive,thinkaloudp0701,4,NaN
2,"""PRABMQV2""",0,617499,1751056,1,"""start""","""01/16/2020 16:42:28.626""","""""",NaN,218467966,Proactive,thinkaloudp0216,4,NaN
3,"""PRABMQV2""",0,616756,1751056,2,"""answer""","""12/12/2019 16:23:18.230""","""1 Not confident at all""",True,217901098,Proactive,thinkaloudp0802,4,NaN
4,"""PRABMQV2""",0,616756,1751056,3,"""end""","""12/12/2019 16:23:18.234""","""""",NaN,217901098,Proactive,thinkaloudp0802,4,NaN

In [3]:
df.dtypes

Problem.ID              object
ProblemStep              int64
User.ID                  int64
Problem.Sub.Part.ID      int64
Order                    int64
Action.Type             object
Timestamp               object
Answer.Text             object
Correctness             object
Problem.Log.ID           int64
Condition               object
Participant_ID          object
Problem                  int64
CorrectAnswer          float64
dtype: object

In [4]:
df['Correctness'].value_counts()

True     703
False     93
Name: Correctness, dtype: int64

In [5]:
df1= df.query('Correctness == False')
df1.head()

,Problem.ID,ProblemStep,User.ID,Problem.Sub.Part.ID,Order,Action.Type,Timestamp,Answer.Text,Correctness,Problem.Log.ID,Condition,Participant_ID,Problem,CorrectAnswer
33,"""PRABMQV2""",1,616590,1751115,2,"""answer""","""12/06/2019 14:35:33.411""","""0.4""",False,217733195,Proactive,thinkaloudp0606,4,0.3
34,"""PRABMQV2""",1,618707,1751115,2,"""answer""","""01/30/2020 15:22:12.129""","""0.4""",False,218852635,Proactive,thinkaloudp1110,4,0.3
35,"""PRABMQV2""",1,617714,1751115,2,"""answer""","""01/17/2020 14:18:37.823""","""0.4""",False,218499907,Proactive,thinkaloudp1006,4,0.3
36,"""PRABMQV2""",1,616590,1751115,4,"""answer""","""12/06/2019 14:36:35.246""",""".4/.9""",False,217733195,Proactive,thinkaloudp0606,4,0.3
38,"""PRABMQV2""",1,618707,1751115,3,"""answer""","""01/30/2020 15:23:10.386""","""0.4""",False,218852635,Proactive,thinkaloudp1110,4,0.3

In [6]:
df2 = df1.groupby(['Problem', 'ProblemStep', 'Answer.Text'], as_index=False).agg(Answer_Counts = ('Answer.Text', 'count'))

In [7]:
df2.columns

Index(['Problem', 'ProblemStep', 'Answer.Text', 'Answer_Counts'], dtype='object')

In [8]:
ruledf  = pd.read_csv("rule_types.csv")
ruledf.head()

   Problem  ProblemStep Rule_type  Rule_order
0        1            0       NaN         NaN
1        1            1        R1         1.0
2        1            2        R2         1.0
3        1            3        R3         1.0
4        2            0       NaN         NaN

In [9]:
df3 = pd.merge(df2, ruledf, how="left", left_on=["Problem", "ProblemStep"], right_on=["Problem", "ProblemStep"])
df3
# Answer.text == unique count

    Problem  ProblemStep Answer.Text  Answer_Counts Rule_type  Rule_order
0         1            1       "4/7"              1        R1         1.0
1         1            1      "8/14"              1        R1         1.0
2         1            2         "2"              5        R2         1.0
3         1            2       "4/7"              1        R2         1.0
4         1            2         "6"              1        R2         1.0
5         1            2      "8/14"              1        R2         1.0
6         2            1     "10/25"              1        R1         2.0
7         2            1        "25"              1        R1         2.0
8         2            1        "35"              1        R1         2.0
9         2            2        "25"              4        R2         2.0
10        2            3       "5/7"              2        R3         2.0
11        4            1     ".4/.1"              2        R4         1.0
12        4            1     ".4/.9"              1        R4         1.0
13        4            1      "0.04"              1        R4         1.0
14        4            1   "0.3/0.9"              1        R4         1.0
15        4            1       "0.4"             18        R4         1.0
16        4            1   "0.4/0.1"              1        R4         1.0
17        4            1   "0.4/0.9"              1        R4         1.0
18        4            3       "0.1"              2        R5         1.0
19        4            3      "0.11"              1        R5         1.0
20        4            3      "0.12"              3        R5         1.0
21        4            3      "0.15"              1        R5         1.0
22        4            3       "0.2"              1        R5         1.0
23        4            3       "0.3"              1        R5         1.0
24        4            3       "0.6"              1        R5         1.0
25        4            3       "0.8"              1        R5         1.0
26        4            3       "0.9"              1        R5         1.0
27        4            3      "3/25"              1        R5         1.0
28        5            1       "0.4"              2        R4         3.0
29        5            1        "15"              1        R4         3.0
30        5            1       "40%"              1        R4         3.0
31        5            3       "0.9"              2        R5         2.0
32        6            1        "40"              1        R4         5.0
33        6            3       "0.3"              1        R5         3.0
34        6            3       "0.9"              1        R5         3.0
35        7            2    "0.1136"              1        R6         1.0
36        7            2      "0.67"              1        R6         1.0
37        7            2      "5/44"              2        R6         1.0
38        7            3      "0.18"              1        R7         1.0
39        7            3       "0.7"              2        R7         1.0
40        7            3    "15/144"              1        R7         1.0
41        7            3    "25/132"              1        R7         1.0
42        7            3     "31/44"              1        R7         1.0
43        8            1      "1/25"              1        R3         5.0
44        8            1       "3/5"              1        R3         5.0
45        9            1       "1/5"              1        R3         6.0
46        9            1      "5/16"              1        R3         6.0
47        9            2    "20/210"              1        R6         3.0
48        9            2    "25/210"              1        R6         3.0
49        9            2      "5/14"              1        R6         3.0
50        9            3    "20/210"              1        R6         4.0
51        9            3      "9/29"              1        R6         4.0
52        9            4      "0.02"              1        R7         3.0
53        9            4      "1/50"              1        R7         3.0
54        9            4    "12/546"              1        R7         3.0
55        9            4   "232/273"              1        R7         3.0
56        9            4     "3/123"              1        R7         3.0
57        9            4      "3/13"              1        R7         3.0
58        9            4   "60/2730"              2        R7         3.0

In [10]:
df4 = pd.merge(df1, ruledf, how="left", left_on=["Problem", "ProblemStep"], right_on=["Problem", "ProblemStep"])
df4

,Problem.ID,ProblemStep,User.ID,Problem.Sub.Part.ID,Order,Action.Type,Timestamp,Answer.Text,Correctness,Problem.Log.ID,Condition,Participant_ID,Problem,CorrectAnswer,Rule_type,Rule_order
0,"""PRABMQV2""",1,616590,1751115,2,"""answer""","""12/06/2019 14:35:33.411""","""0.4""",False,217733195,Proactive,thinkaloudp0606,4,0.30,R4,1.0
1,"""PRABMQV2""",1,618707,1751115,2,"""answer""","""01/30/2020 15:22:12.129""","""0.4""",False,218852635,Proactive,thinkaloudp1110,4,0.30,R4,1.0
2,"""PRABMQV2""",1,617714,1751115,2,"""answer""","""01/17/2020 14:18:37.823""","""0.4""",False,218499907,Proactive,thinkaloudp1006,4,0.30,R4,1.0
3,"""PRABMQV2""",1,616590,1751115,4,"""answer""","""12/06/2019 14:36:35.246""",""".4/.9""",False,217733195,Proactive,thinkaloudp0606,4,0.30,R4,1.0
4,"""PRABMQV2""",1,618707,1751115,3,"""answer""","""01/30/2020 15:23:10.386""","""0.4""",False,218852635,Proactive,thinkaloudp1110,4,0.30,R4,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
88,"""PRABNTR5""",1,617498,1801858,2,"""answer""","""01/16/2020 15:23:13.931""","""15""",False,218466549,Reactive,thinkaloudp1212,5,0.15,R4,3.0
89,"""PRABNTR5""",3,618045,1801860,2,"""answer""","""01/23/2020 16:27:19.857""","""0.9""",False,218632003,Reactive,thinkaloudp0912,5,0.40,R5,2.0
90,"""PRABNTR5""",3,619680,1801860,2,"""answer""","""02/17/2020 16:03:29.363""","""0.9""",False,219301256,Reactive,thinkaloudp0213,5,0.40,R5,2.0
91,"""PRABNTR6""",3,616514,1801863,2,"""answer""","""12/05/2019 13:16:25.446""","""0.3""",False,217672371,Reactive,thinkaloudp0421,6,0.50,R5,3.0
92,"""PRABNTR6""",3,616753,1801863,2,"""answer""","""12/12/2019 11:58:42.354""","""0.9""",False,217891718,Reactive,thinkaloudp0101,6,0.50,R5,3.0

In [11]:
contigency = pd.crosstab(index = df4["Answer.Text"], columns = df4["Rule_type"])
contigency

Rule_type    R1  R2  R3  R4  R5  R6  R7
Answer.Text
".4/.1"       0   0   0   2   0   0   0
".4/.9"       0   0   0   1   0   0   0
"0.02"        0   0   0   0   0   0   1
"0.04"        0   0   0   1   0   0   0
"0.1"         0   0   0   0   2   0   0
"0.11"        0   0   0   0   1   0   0
"0.1136"      0   0   0   0   0   1   0
"0.12"        0   0   0   0   3   0   0
"0.15"        0   0   0   0   1   0   0
"0.18"        0   0   0   0   0   0   1
"0.2"         0   0   0   0   1   0   0
"0.3"         0   0   0   0   2   0   0
"0.3/0.9"     0   0   0   1   0   0   0
"0.4"         0   0   0  20   0   0   0
"0.4/0.1"     0   0   0   1   0   0   0
"0.4/0.9"     0   0   0   1   0   0   0
"0.6"         0   0   0   0   1   0   0
"0.67"        0   0   0   0   0   1   0
"0.7"         0   0   0   0   0   0   2
"0.8"         0   0   0   0   1   0   0
"0.9"         0   0   0   0   4   0   0
"1/25"        0   0   1   0   0   0   0
"1/5"         0   0   1   0   0   0   0
"1/50"        0   0   0   0   0   0   1
"10/25"       1   0   0   0   0   0   0
"12/546"      0   0   0   0   0   0   1
"15"          0   0   0   1   0   0   0
"15/144"      0   0   0   0   0   0   1
"2"           0   5   0   0   0   0   0
"20/210"      0   0   0   0   0   2   0
"232/273"     0   0   0   0   0   0   1
"25"          1   4   0   0   0   0   0
"25/132"      0   0   0   0   0   0   1
"25/210"      0   0   0   0   0   1   0
"3/123"       0   0   0   0   0   0   1
"3/13"        0   0   0   0   0   0   1
"3/25"        0   0   0   0   1   0   0
"3/5"         0   0   1   0   0   0   0
"31/44"       0   0   0   0   0   0   1
"35"          1   0   0   0   0   0   0
"4/7"         1   1   0   0   0   0   0
"40"          0   0   0   1   0   0   0
"40%"         0   0   0   1   0   0   0
"5/14"        0   0   0   0   0   1   0
"5/16"        0   0   1   0   0   0   0
"5/44"        0   0   0   0   0   2   0
"5/7"         0   0   2   0   0   0   0
"6"           0   1   0   0   0   0   0
"60/2730"     0   0   0   0   0   0   2
"8/14"        1   1   0   0   0   0   0
"9/29"        0   0   0   0   0   1   0

In [12]:
chi2_contingency(contigency)

(510.57000000000005,
 3.7341965711218174e-13,
 300,
 array([[0.10752688, 0.25806452, 0.12903226, 0.64516129, 0.3655914 ,
         0.19354839, 0.30107527],
        [0.05376344, 0.12903226, 0.06451613, 0.32258065, 0.1827957 ,
         0.09677419, 0.15053763],
        [0.05376344, 0.12903226, 0.06451613, 0.32258065, 0.1827957 ,
         0.09677419, 0.15053763],
        [0.05376344, 0.12903226, 0.06451613, 0.32258065, 0.1827957 ,
         0.09677419, 0.15053763],
        [0.10752688, 0.25806452, 0.12903226, 0.64516129, 0.3655914 ,
         0.19354839, 0.30107527],
        [0.05376344, 0.12903226, 0.06451613, 0.32258065, 0.1827957 ,
         0.09677419, 0.15053763],
        [0.05376344, 0.12903226, 0.06451613, 0.32258065, 0.1827957 ,
         0.09677419, 0.15053763],
        [0.16129032, 0.38709677, 0.19354839, 0.96774194, 0.5483871 ,
         0.29032258, 0.4516129 ],
        [0.05376344, 0.12903226, 0.06451613, 0.32258065, 0.1827957 ,
         0.09677419, 0.15053763],
        [0.05376344, 0.12903226, 0.06451613, 0.32258065, 0.1827957 ,
         0.09677419, 0.15053763],
        [0.05376344, 0.12903226, 0.06451613, 0.32258065, 0.1827957 ,
         0.09677419, 0.15053763],
        [0.10752688, 0.25806452, 0.12903226, 0.64516129, 0.3655914 ,
         0.19354839, 0.30107527],
        [0.05376344, 0.12903226, 0.06451613, 0.32258065, 0.1827957 ,
         0.09677419, 0.15053763],
        [1.07526882, 2.58064516, 1.29032258, 6.4516129 , 3.65591398,
         1.93548387, 3.01075269],
        [0.05376344, 0.12903226, 0.06451613, 0.32258065, 0.1827957 ,
         0.09677419, 0.15053763],
        [0.05376344, 0.12903226, 0.06451613, 0.32258065, 0.1827957 ,
         0.09677419, 0.15053763],
        [0.05376344, 0.12903226, 0.06451613, 0.32258065, 0.1827957 ,
         0.09677419, 0.15053763],
        [0.05376344, 0.12903226, 0.06451613, 0.32258065, 0.1827957 ,
         0.09677419, 0.15053763],
        [0.10752688, 0.25806452, 0.12903226, 0.64516129, 0.3655914 ,
         0.19354839, 0.30107527],
        [0.05376344, 0.12903226, 0.06451613, 0.32258065, 0.1827957 ,
         0.09677419, 0.15053763],
        [0.21505376, 0.51612903, 0.25806452, 1.29032258, 0.7311828 ,
         0.38709677, 0.60215054],
        [0.05376344, 0.12903226, 0.06451613, 0.32258065, 0.1827957 ,
         0.09677419, 0.15053763],
        [0.05376344, 0.12903226, 0.06451613, 0.32258065, 0.1827957 ,
         0.09677419, 0.15053763],
        [0.05376344, 0.12903226, 0.06451613, 0.32258065, 0.1827957 ,
         0.09677419, 0.15053763],
        [0.05376344, 0.12903226, 0.06451613, 0.32258065, 0.1827957 ,
         0.09677419, 0.15053763],
        [0.05376344, 0.12903226, 0.06451613, 0.32258065, 0.1827957 ,
         0.09677419, 0.15053763],
        [0.05376344, 0.12903226, 0.06451613, 0.32258065, 0.1827957 ,
         0.09677419, 0.15053763],
        [0.05376344, 0.12903226, 0.06451613, 0.32258065, 0.1827957 ,
         0.09677419, 0.15053763],
        [0.2688172 , 0.64516129, 0.32258065, 1.61290323, 0.91397849,
         0.48387097, 0.75268817],
        [0.10752688, 0.25806452, 0.12903226, 0.64516129, 0.3655914 ,
         0.19354839, 0.30107527],
        [0.05376344, 0.12903226, 0.06451613, 0.32258065, 0.1827957 ,
         0.09677419, 0.15053763],
        [0.2688172 , 0.64516129, 0.32258065, 1.61290323, 0.91397849,
         0.48387097, 0.75268817],
        [0.05376344, 0.12903226, 0.06451613, 0.32258065, 0.1827957 ,
         0.09677419, 0.15053763],
        [0.05376344, 0.12903226, 0.06451613, 0.32258065, 0.1827957 ,
         0.09677419, 0.15053763],
        [0.05376344, 0.12903226, 0.06451613, 0.32258065, 0.1827957 ,
         0.09677419, 0.15053763],
        [0.05376344, 0.12903226, 0.06451613, 0.32258065, 0.1827957 ,
         0.09677419, 0.15053763],
        [0.05376344, 0.12903226, 0.06451613, 0.32258065, 0.1827957 ,
         0.09677419, 0.15053763],
        [0.05376344, 0.12903226, 0.06451613, 0.32258065, 0.1827957 ,
         0.09677419, 0.15053763],
        [0.05376344, 0.12903226, 0.06451613, 0.32258065, 0.1827957 ,
         0.09677419, 0.15053763],
        [0.05376344, 0.12903226, 0.06451613, 0.32258065, 0.1827957 ,
         0.09677419, 0.15053763],
        [0.10752688, 0.25806452, 0.12903226, 0.64516129, 0.3655914 ,
         0.19354839, 0.30107527],
        [0.05376344, 0.12903226, 0.06451613, 0.32258065, 0.1827957 ,
         0.09677419, 0.15053763],
        [0.05376344, 0.12903226, 0.06451613, 0.32258065, 0.1827957 ,
         0.09677419, 0.15053763],
        [0.05376344, 0.12903226, 0.06451613, 0.32258065, 0.1827957 ,
         0.09677419, 0.15053763],
        [0.05376344, 0.12903226, 0.06451613, 0.32258065, 0.1827957 ,
         0.09677419, 0.15053763],
        [0.10752688, 0.25806452, 0.12903226, 0.64516129, 0.3655914 ,
         0.19354839, 0.30107527],
        [0.10752688, 0.25806452, 0.12903226, 0.64516129, 0.3655914 ,
         0.19354839, 0.30107527],
        [0.05376344, 0.12903226, 0.06451613, 0.32258065, 0.1827957 ,
         0.09677419, 0.15053763],
        [0.10752688, 0.25806452, 0.12903226, 0.64516129, 0.3655914 ,
         0.19354839, 0.30107527],
        [0.10752688, 0.25806452, 0.12903226, 0.64516129, 0.3655914 ,
         0.19354839, 0.30107527],
        [0.05376344, 0.12903226, 0.06451613, 0.32258065, 0.1827957 ,
         0.09677419, 0.15053763]]))

In [13]:
df5  = pd.read_csv("FalseLook.csv") 
df5 = df5.set_index('Answers')
df5

         R1  R2  R3  R4  R5  R6  R7
Answers
4.00      0   0   0   3   0   0   0
0.40      1   0   0  23   0   1   0
0.02      0   0   0   0   0   0   4
0.04      0   0   1   1   0   0   0
0.10      0   0   0   0   7   6   1
0.20      0   0   1   0   2   0   3
0.30      0   0   1   1   2   0   0
0.60      1   1   1   0   1   0   0
0.70      0   0   2   0   0   0   3
0.80      0   0   0   0   1   0   1
0.90      0   0   0   0   4   0   0
15.00     0   0   0   1   0   0   0
2.00      0   5   0   0   0   0   0
25.00     1   4   0   0   0   0   0
35.00     1   0   0   0   0   0   0
40.00     0   0   0   1   0   0   0
6.00      0   1   0   0   0   0   0

In [14]:
chi2_contingency(df5)

(266.97825943104516,
 4.960809263909004e-18,
 96,
 array([[0.13793103, 0.37931034, 0.20689655, 1.03448276, 0.5862069 ,
         0.24137931, 0.4137931 ],
        [1.14942529, 3.16091954, 1.72413793, 8.62068966, 4.88505747,
         2.01149425, 3.44827586],
        [0.18390805, 0.50574713, 0.27586207, 1.37931034, 0.7816092 ,
         0.32183908, 0.55172414],
        [0.09195402, 0.25287356, 0.13793103, 0.68965517, 0.3908046 ,
         0.16091954, 0.27586207],
        [0.64367816, 1.77011494, 0.96551724, 4.82758621, 2.73563218,
         1.12643678, 1.93103448],
        [0.27586207, 0.75862069, 0.4137931 , 2.06896552, 1.17241379,
         0.48275862, 0.82758621],
        [0.18390805, 0.50574713, 0.27586207, 1.37931034, 0.7816092 ,
         0.32183908, 0.55172414],
        [0.18390805, 0.50574713, 0.27586207, 1.37931034, 0.7816092 ,
         0.32183908, 0.55172414],
        [0.22988506, 0.63218391, 0.34482759, 1.72413793, 0.97701149,
         0.40229885, 0.68965517],
        [0.09195402, 0.25287356, 0.13793103, 0.68965517, 0.3908046 ,
         0.16091954, 0.27586207],
        [0.18390805, 0.50574713, 0.27586207, 1.37931034, 0.7816092 ,
         0.32183908, 0.55172414],
        [0.04597701, 0.12643678, 0.06896552, 0.34482759, 0.1954023 ,
         0.08045977, 0.13793103],
        [0.22988506, 0.63218391, 0.34482759, 1.72413793, 0.97701149,
         0.40229885, 0.68965517],
        [0.22988506, 0.63218391, 0.34482759, 1.72413793, 0.97701149,
         0.40229885, 0.68965517],
        [0.04597701, 0.12643678, 0.06896552, 0.34482759, 0.1954023 ,
         0.08045977, 0.13793103],
        [0.04597701, 0.12643678, 0.06896552, 0.34482759, 0.1954023 ,
         0.08045977, 0.13793103],
        [0.04597701, 0.12643678, 0.06896552, 0.34482759, 0.1954023 ,
         0.08045977, 0.13793103]]))